# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  eventstore:
    image: eventstore/eventstore:release-5.0.7
    restart: unless-stopped
    ports:
      - 1113:1113
      - 2113:2113
